Console.WriteLine("(Tudubom)");
Console.WriteLine("(Toca do cartel, Mãolee no beat)");
Console.WriteLine("");
Console.WriteLine("");
Console.WriteLine("Oh-oh-uou-uou-uh");
Console.WriteLine("Oh-oh-uou-uou-uh");
Console.WriteLine("Oh-oh-uou-uou-uh");
Console.WriteLine("Uou-uou-oh-ohuh");
Console.WriteLine("");
Console.WriteLine("Eis o Ret aceso, irmão");
Console.WriteLine("Na luz da perdição, me encontro e pago o preço");
Console.WriteLine("Vou além, fumo um");
Console.WriteLine("Subo e desço, esclareço alguém");
Console.WriteLine("Confundo alguns, desobedeço");
Console.WriteLine("Já disse, vou repetir pra você");
Console.WriteLine("Quanto menos me ouvir, mais e melhor eu vou dizer");
Console.WriteLine("Tô vivo no mic mais uma vez, cada linha um tiro");
Console.WriteLine("Tenho dez pentes de dezesseis");
Console.WriteLine("Acende um fino, entre hi-hats e pratos");
Console.WriteLine("Corre daqui com seu papinho reto e chato");
Console.WriteLine("Tô no páreo, caralho, fumando droga");
Console.WriteLine("É o rap carioca chegando, tocando o zaralho");
Console.WriteLine("Quem reclamar vai perder");
Console.WriteLine("Se o mundo não te entendeu, cê não se fez entender");
Console.WriteLine("Atrás da glória, trampando o dia inteiro");
Console.WriteLine("Na prática, a vitória é de quem pega primeiro");
Console.WriteLine("Sou tiro que arranca máscara");
Console.WriteLine("Meu partido sou eu, tipo Hezbollah");
Console.WriteLine("Tô no TTK, manda vir me pegar");
Console.WriteLine("Seu respeito já não basta, só seu medo bastará");
Console.WriteLine("");
Console.WriteLine("Vivaz não pode errar");
Console.WriteLine("Linda, vem me curar");
Console.WriteLine("Uou-uou-uh, vivaz não pode errar");
Console.WriteLine("Sou mais um neurótico de guerra");
Console.WriteLine("");
Console.WriteLine("Pisando na grama, roubando rosas");
Console.WriteLine("As melhores ideias são as perigosas");
Console.WriteLine("Se acomode ou se incomode");
Console.WriteLine("A fé não vale de nada pra mente preguiçosa");
Console.WriteLine("Eles querem o bem, eu quero a verdade");
Console.WriteLine("Vivem pra deixar bens, eu pra deixar saudade");
Console.WriteLine("Meu som sai da sagacidade, pra ser bom");
Console.WriteLine("É preciso sentir raiva da mediocridade");
Console.WriteLine("Sonhar vicia, parar de sonhar e agir");
Console.WriteLine("É aonde tá a sabedoria");
Console.WriteLine("Eles falam demais, mas falam em vão");
Console.WriteLine("O vivaz sabe que o silêncio tem sempre razão");
Console.WriteLine("É só entender");
Console.WriteLine("Quem escuta não ouve, quem olha não vê");
Console.WriteLine("Do submundo vou subverter");
Console.WriteLine("Ou você intimida o mundo");
Console.WriteLine("Ou o mundo intimida você");
Console.WriteLine("Ligado e perigoso");
Console.WriteLine("Se eles são iluminados, eu sou luminoso");
Console.WriteLine("Pode dizer que meu sonho é inútil");
Console.WriteLine("Os loucos românticos sempre riem por último");
Console.WriteLine("");
Console.WriteLine("Vivaz não pode errar");
Console.WriteLine("Linda, vem me curar");
Console.WriteLine("Uou-uou-uh, vivaz não pode errar");
Console.WriteLine("Sou mais um neurótico de guerra");
Console.WriteLine("");
Console.WriteLine("De guerra, uou-uou-uh");
Console.WriteLine("De guerra, uou-uou");
Console.WriteLine("De guerra, uou-uou-uh");
Console.WriteLine("De guerra, uou");
Console.WriteLine("");
Console.WriteLine("");
Console.WriteLine("Composição: Filipe Ret.");